name = "journo-status-service"
main = "src/index.ts"
compatibility_date = "2024-09-01"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "*"
CLOUDFLARE_ACCOUNT_ID = "d2a246f376937c8a6d58d1f75925ac4b"
CLOUDFLARE_PAGES_PROJECT = "spbzorro"
COMMENTS_API_URL = "https://journo-comments.journo-sentinel.workers.dev"

[[kv_namespaces]]
binding = "STATUS_KV"
id = "218a75a0460643d39040e6a2fd41f593"
